### ISSUE TITLE
estimation of alpha in code

### ISSUE THREAD

**Issue by daki11** [gersteinlab/sigLASSO#1]
Hello,

i have been goint through your papper on sigLasso and through your code. I have an issue understanding implementation of alpha parameter estimation. In paper it is calculated from variance, alpha = 1/variance=(n-k)(MSE)/n,  where n is total number of signatures and k is equal to number of non zero coefficients. In code, however, it is given by fallowing lines:

1) alpha=max(1/sum((p_hat-p_star_hat)^2)/K*(K-length(which(coef_hat>0))),  alpha_min)		
2) alpha=1/alpha

In line 1) K is equal to number of signatures, so K is basicaly n. Therefore, if we only take part where alpha is estimated, we have that alpha is estimated as 
alpha = 1/(MSE)/n*(n-k) from line 1) and after inverting in line 2) we have:
alpha = (MSE)*n/(n-k) which is not same formula as in the paper.

Please help me understand this.

Thanks in advance,
Dalibor

**Comment by ShantaoL** [comment]
Hi Dalibor,

Thanks for pointing this out. I later realized that I put up an older version of the code and it has uncorrected issues in it.

1) You are right about the inverting alpha, line 2 should go away.
2) The usage of MSE is confusing. Basically, the variance estimator should be sum(Y-Xbeta^hat)^2/(n-k). 

I have solved the issue in the code and we will remove the usage of MSE in the manuscript.

**Comment by daki11** [comment]
Thank you for your fast response!

I have few more questions, i am insecure about some conclusions of mine :)

 q1):     First, MSE = sum(Y-Xbeta^hat)^2 , right? and variance is basicaly MSE/(n-k) ?

q2):       Also for lines 1) and 2), as far as i can see, in line 1) alpha calculated is actually sigma, and then in line 2) (when result of line 1 is inverted) we effectively get "real" parameter alpha that is calculated by inverted estimated sigma, as explained in paper in part about parameter tuning. Am i right about this? 

q3):     I am mostly confused with formula given in paper stating sigma = n/(n-k)/(MSE) while in code formula given for sigma in line 1)  sigma = (n-k)/(MSE)/n which is not same formula. Also, i am bit confused about sigma itself, by looking at crterion function(maximum likelihood) i get idea that sigma is variance, but when looking at how it is calculated in paper it looks to me that it is 1/variance and that alpha is actually a variance?

q4):    Also, q3 further confuses me about line 1) where first argument of "max" function looks like sigma but is compared with alpha(inside "max" function) which is inverse of sigma?

Thanks in advance, i am sorry if my questions are clumsy, i still have ways to go in fields of statistics :)

best regards,
Dalibor

**Comment by ShantaoL** [comment]
Hi Dalibor,

1) MSE is mean square error, so MSE = SSE(sum square error)/n. 
The variance is SSE/(n-k) =  MSE*n/(n-k). The use of MSE as a notation in the paper is a bit confusing, I will fix that part.
2) Yes. In practice, we noticed it is better to scale up alpha by a factor. A good number is 10. Otherwise, the model is overly confident in the signature fitting. I will update the code shortly.
3) alpha = 1/variance, which controls the strength between the two optimization tasks. 

Shantao

**Comment by daki11** [comment]
It is all clear to me now, thank you for all the answers!!

best regards,
Dalibor
