### ISSUE TITLE
Fail due to glmnet error

### ISSUE THREAD

**Issue by lybird300** [gersteinlab/siglasso#1]
Hello, when I used siglasso on my data, the glmnet package threw an error: 

> Error in elnet(x, is.sparse, ix, jx, y, weights, offset, type.gaussian,   y is constant; gaussian glmnet fails at standardization step

What do you think might be the problem? What can I do to solve it? Thank you!

p.s., I'm using a combination of our exome sequencing data and several TCGA cohorts

**Comment by ShantaoL** [comment]
Hey,

This is likely caused by some of the very-low-counts samples get really badly fitted and the coefficients shrink to all zeros when iterating between the two objective functions, esp. during cross-validation. 

I have put a patch on this, it should be okay now.
