### ISSUE TITLE
Mutational signatures v3 upgrade

### ISSUE THREAD

**Issue by dalibor49** [gersteinlab/siglasso#2]
Hello,

when will siglasso be upgraded to work with mutational signatures v3?

Best regards,
Dalibor

**Comment by ShantaoL** [comment]
Hey Dalibor, 

We have updated the package to 1.1, now it supports signatures v3 from COSMIC (there are two set, one for the whole genome, one for exome only). 
You can check how to use them by ```?siglasso```
