### ISSUE TITLE
`siglasso` function takes too long running time  

### ISSUE THREAD

**Issue by likelet** [gersteinlab/siglasso#5]
i got mutations from almost 1000 samples, then  try `siglasso ` to get the mutational signature as suggested. However, it took more than 12 hours, and it is still running until now. 
I have no idea whether it is ok in this case. 
here is the log the function returns 
   
```
 my_sigs <- siglasso(tempspec,plot=F)
[1] "No signature supplied, will use COSMIC v2 signatures, we also supply v2 priors in the package"
[1] "There are 942 samples
```
look forward to your reply. 
@ShantaoL

**Comment by ShantaoL** [comment]
Hi, 

I believe the program is running. But 1000 samples unfinished in 12 hours does sound a bit strange. Could you try a few samples first and see it works? Also, you can interrupt the current program and see what it is running.

**Comment by likelet** [comment]
Hi @ShantaoL,
thanks for the reply. It is still running until now.  I cancelled the program and rerun the analysis with only 10 samples, it finished in a few seconds with output expected. So any suggestion for my case?

**Comment by likelet** [comment]
I try 800 samples, it works well, but when the number comes to 875, it stuck again.  
may be related to the sample? 

I will try to figure it out, and let you know when it is done.

**Comment by ShantaoL** [comment]
I think there is one (or more) sample between 801-875 causing the hang-up. 
You can try to feed the rest one-by-one to the program (or binary search) and see what actually causes the hang-up. 

Please do share your findings, it will help sigLASSO to be more robust in the future. Thanks!

**Comment by likelet** [comment]
> I think there is one (or more) sample between 801-875 causing the hang-up.
> You can try to feed the rest one-by-one to the program (or binary search) and see what actually causes the hang-up.
> 
> Please do share your findings, it will help sigLASSO to be more robust in the future. Thanks!

I Found the sample  with only one mutation that result in such phenomenon, which should be excluded in data preprocessing.
I don't know why a sample with one mutation could trigger this problem, but I think the function should at a default parameter to filter the sample with too little mutations, May be 2?

**Comment by ShantaoL** [comment]
Thanks for sharing this! I agree with you we should have an error catch early on for this. 
In general, samples with mutation counts under 10ish are unsuitable to call signatures, it won't be reliable.
